export { default as Header } from './Header/Header'
export { default as SideBar } from './SideBar/SideBar'
export { default as Info } from './Info/Info'
export { default as GoBack } from './GoBack/GoBack'
export { default as Modal } from './Modal/Modal'